
apiVersion: v1
kind: Pod
metadata:
  name: foo
  namespace: vso-example
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: secrets
      mountPath: "/etc/secrets"
      readOnly: true
  volumes:
  - name: secrets
    secret:
      secretName: foo
      optional: false

---

apiVersion: v1
kind: Pod
metadata:
  name: bar
  namespace: vso-example
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: secrets
      mountPath: "/etc/secrets"
      readOnly: true
  volumes:
  - name: secrets
    secret:
      secretName: bar
      optional: false