# https://developer.hashicorp.com/vault/docs/platform/k8s/vso/api-reference#vaultstaticsecret

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: vso-example
  name: vaultstaticsecret-foo
spec:
  vaultAuthRef: example
  mount: secretstorename
  type: kv-v2
  path: foo
  refreshAfter: 5s
  destination:
    name: foo
    create: true

---

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: vso-example
  name: vaultstaticsecret-bar
spec:
  vaultAuthRef: example
  mount: secretstorename
  type: kv-v2
  path: bar
  refreshAfter: 5s
  destination:
    name: bar
    # Create the destination Secret. If the Secret already exists this should be set to false.
    create: true
